name:                dawn
version:             0.1.0.0
github:              "githubuser/dawn"
license:             BSD-3-Clause
author:              "Agakitsune, nourrysebastienN"
maintainer:          "raphael.turpin@epitech.eu, nourry.sebastien@epitech.eu"
copyright:           "2023 Agakitsune, nourrysebastienN"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dawn#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- monadplus
- ghc
- bytestring
- hashable
- unordered-containers
- ansi-terminal
- transformers
- filepath
- directory
- process

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
  - Monoparsec
  - Monoparsec.State
  - Monoparsec.Stream
  - Monoparsec.Token
  - Monoparsec.Message
  - Monoparsec.Debug

  - System.Console.Hawk

  - Dawn
  - Dusk
  - Twillight
  - Option
  other-modules:
  - Monoparsec.Misc
  - Monoparsec.Message.Item
  - Monoparsec.Message.Range
  - Monoparsec.Message.Reason
  - Monoparsec.Message.Type
  - Monoparsec.Monad
  - Monoparsec.Monad.MonadParsec
  - Monoparsec.Monad.Option

  - Data.Hawk.Any
  - Data.Hawk.Any.Prelude
  - System.Console.Hawk.Annotate
  - System.Console.Hawk.Default
  - System.Console.Hawk.Explicit
  - System.Console.Hawk.Explicit.Complete
  - System.Console.Hawk.Explicit.ExpandArgsAt
  - System.Console.Hawk.Explicit.Help
  - System.Console.Hawk.Explicit.Process
  - System.Console.Hawk.Explicit.SplitJoin
  - System.Console.Hawk.Explicit.Type
  - System.Console.Hawk.Helper
  - System.Console.Hawk.Implicit
  - System.Console.Hawk.Implicit.Extra
  - System.Console.Hawk.Implicit.Global
  - System.Console.Hawk.Implicit.Local
  - System.Console.Hawk.Implicit.Reader
  - System.Console.Hawk.Implicit.Reform
  - System.Console.Hawk.Implicit.Type
  - System.Console.Hawk.Implicit.UI
  - System.Console.Hawk.Text
  - System.Console.Hawk.Verbosity

executables:
  dawn-exe:
    main:                Main.hs
    source-dirs:
    - dawn-app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dawn
  dawnc-exe:
    main:               Main.hs
    source-dirs:
    - dawnc-app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dawn
  prez-exe:
    main:               Main.hs
    source-dirs:
    - prez
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dawn

tests:
  dawn-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dawn
    - HUnit
