name: Glados
on:
  push:
    branches:
      - UnitTest
      - dev
      - main

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

          #    - name: Install stack (MacOS)
          #      run: curl -sSL https://get.haskellstack.org/ | sh
          #      if: matrix.os == 'macos-10.15'

      - name: Install stack (Windows)
        run: choco install haskell-stack
        if: matrix.os == 'windows-2019'

          # - name: Cache dependencies (Unix)
          #   uses: actions/cache@v1
          #   if: matrix.os != 'windows-2019'
          #   with:
          #     path: ~/.stack
          #     key: ${{ runner.os }}-store-${{ hashFiles('generator/stack.yaml.lock') }}-${{ hashFiles('generator/generator.cabal') }}

      - name: Cache dependencies (Windows)
        uses: actions/cache@v1
        if: matrix.os == 'windows-2019'
        with:
          path: 'C:\Users\runneradmin\AppData\Roaming\stack'
          key: ${{ runner.os }}-store-${{ hashFiles('generator/stack.yaml.lock') }}-${{ hashFiles('generator/generator.cabal') }}

      - name: Cache GHC (Windows)
        uses: actions/cache@v1
        if: matrix.os == 'windows-2019'
        with:
          path: 'C:\Users\runneradmin\AppData\Local\Programs\stack'
          key: ghc-${{ hashFiles('generator/stack.yaml.lock') }}

      - name: Build Glados
        run: |
          stack build
          ls


#     - name: Upload artifact
#       uses: actions/upload-artifact@v1
#       with:
#         name: generator-${{ runner.os }}
#         path: package
