on:
  push:
    branches:
      - main
jobs:
  publish-release:
    runs-on: ubuntu-latest

    container:
      image: epitechcontent/epitest-docker
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      #     - uses: rymndhng/release-on-push-action@master
      #  with:
      #    bump_version_scheme: minor
